name: "Update 3rd-Party Lists"

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync-files:
    name: "Run sync"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Run lister"
        run: |
          DIVIDING_LINE="-----------------------------------------------------------------------------"
          DATABASES="soarpkgs-toolpacks"
          for db in $DATABASES; do
             cd "$db" || exit 1
             echo "$DIVIDING_LINE"
             echo "◆ Updating \"$db\"..."
             ./lister.sh
             echo "$DIVIDING_LINE"
          done

      - name: "Push to Source"
        run: |
          git config --global user.name "ivan-hc"
          git config --global user.email "noreply@github.com"
          git add */*.md */*.sh
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "Sync files from source repository"
            git push && echo "Sync to Source succeeded" >> $GITHUB_STEP_SUMMARY
          fi
